---

sudo: True
language: 'python'
python: '2.7'

virtualenv:
    system_site_packages: true

before_install:
  - env
  - df -h
  - mount
  - cat /proc/meminfo
  - cat /proc/cpuinfo
  - ip address
  - ip route
  - uname -a
  - ps aufx
  - pstree -up

script:
  - sleep 1


## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
