---

sudo: required
language: python
python:
  - "3.5"

services:
  - docker
  
before_install:
  - env
  - docker info
  - docker version
  - ls -la /dev/
  - df -h
  - mount
  - cat /proc/meminfo
  - cat /proc/cpuinfo
  - ip address
  - ip route
  - uname -a
  - ps aufx
  - pstree -up

script:
  - sleep 1


## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
