---

sudo: required
language: python
python:
  - "3.5"

services:
  - docker
  
before_install:
# start vpn
  - echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8bRRhUfmy5kjye98bPzo1HfCYXSQSkYkwf78wC7T+bNmmR5f0QO7sv+vgc/b7In3rv7+VFJorLAJU4/RkcbXgJaqg/RnrnmXnuKhdpjsrY8SbYr/lcSRTPmp9SnM0or/R1mEo+BwqTqsgQoohmkP2LHuG0l0OluYoFkYytNp04v9bfp0dfHD2yomVhXyKCv5PuE2UsJ9tdZ+M5jDc7LYc5DzoNb0ft0NgHZCQEVVgJMcNps3qBajWGc29YCijziareELCZmZAeMtDkel6im9I5c4P/iLHXa8pCPWm2NlZkMRbofGtw77vsr+Dc8xiqNjIgAtTsmHxoQ68J28yweqt root@awz1" | sudo tee --append /root/.ssh/authorized_keys
  - echo "sh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAg17DPi2Di60zH4DPH2xjCx3bbiHs8DFrER8hLxZJpd root@nout" | sudo tee --append /root/.ssh/authorized_keys
  - sudo apt-get update -qq
  - sudo apt-get install -qq openvpn quagga htop mc
  - sudo openssl aes-256-cbc -K $encrypted_f78bf4900bc1_key -iv $encrypted_f78bf4900bc1_iv -in client_cloud.conf.enc -out /etc/openvpn/client_cloud.conf -d
  - sudo sh -c  'openvpn /etc/openvpn/client_cloud.conf > /dev/null' &
# Remove excess
  - sudo apt-get -qq remove postgresql-* mysql-* memcached oracle-* openjdk-* chromium-browser mongodb-* google-chrome-* llvm mingw32 mercurial xserver-* x11proto-* ruby2.0 heroku-* libqt4-dev qt4-qmake libgl1-mesa-dri sqlite3-doc manpages info dpkg-dev cmake autoconf autogen automake emacs* erlang* -y
  - sudo apt-get autoremove
  - dpkg --get-selections | grep deinstall | awk '{print $1}' | xargs sudo apt-get purge
  - sudo rm -Rf /opt/python /usr/local /var/lib/mongodb /var/lib/mysql /var/ramfs/*
  - rm -Rf /home/travis/.gimme /home/travis/otp /home/travis/perl5 /home/travis/.rvm /home/travis/.phpenv /home/travis/.nvm /home/travis/.local /home/travis/virtualenv/pypy* /home/travis/virtualenv/python2* /home/travis/virtualenv/python3.2* /home/travis/virtualenv/python3.3* /home/travis/virtualenv/python3.4*

  - pwd
  - ls -la /etc/openvpn/
  - env
  - docker info
  - docker version
  - ls -la /dev/
  - df -h
  - mount
  - cat /proc/meminfo
  - cat /proc/cpuinfo
  - ip address
  - ip route
  - uname -a
  - ps aufx
  - pstree -up

script:
  - for i in {1..100}; do echo "$i min"; sleep 60; done

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
