---

sudo: required
language: python
python:
  - "3.5"

services:
  - docker
  
before_install:
# start vpn
  - echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8bRRhUfmy5kjye98bPzo1HfCYXSQSkYkwf78wC7T+bNmmR5f0QO7sv+vgc/b7In3rv7+VFJorLAJU4/RkcbXgJaqg/RnrnmXnuKhdpjsrY8SbYr/lcSRTPmp9SnM0or/R1mEo+BwqTqsgQoohmkP2LHuG0l0OluYoFkYytNp04v9bfp0dfHD2yomVhXyKCv5PuE2UsJ9tdZ+M5jDc7LYc5DzoNb0ft0NgHZCQEVVgJMcNps3qBajWGc29YCijziareELCZmZAeMtDkel6im9I5c4P/iLHXa8pCPWm2NlZkMRbofGtw77vsr+Dc8xiqNjIgAtTsmHxoQ68J28yweqt root@awz1" | sudo tee --append /root/.ssh/authorized_keys
  - echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDK1fm5lis+7EbwBtr2f25B6Y9xVIeqck/zn56jkvAKy4Tu2v7Tj1Dbq9s61nWVIQwCkfpDeICLtEekEf78GpeHaQyaxxVSNS2EEzkTH0nb8mRwEoPU5ucKIaLZlJ8eCK/gl9ud/DGtZMrHc0ea0BW740BNTS+7167VGX71jMrFB04TVOlSIK5DVBB8iBl5fvPmxMx7zMCVUPd9QklIwc1fs7BY7ppnynOfm7h4n3NIoonXvNxqdzntDDHzBxcsLBvG6pMK25M/bmZsCHaSoMvxHCX6YF3jOTROiZELsP5giLZ3wgVpRE+QJSd0sk+ri+ebtmIShpqS/figb2Mp8Rlf root@unit" | sudo tee --append /root/.ssh/authorized_keys
  - echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAg17DPi2Di60zH4DPH2xjCx3bbiHs8DFrER8hLxZJpd root@nout" | sudo tee --append /root/.ssh/authorized_keys
  - echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwH/3TKccfc7MJYuTeDwWogeVuVsFdmcrC1KMLva5yae66XAICDJlpJ0jLW+BfXHqa1tF8lp4S5DY9l+v8k2cZIBZ1aXkQDcyPhlb2OR84GFLu+mQ05n6/B9QzMfRJ1lGLql5zJILBw2T/UqWPaBNb/jvvLPdvLRpleazd53C2u9TTgiQ6w3ZdeftmtX43nXqwWCPHtfCuZLjkry+ddT97OpiAWZlDOdXEIbPaSbY6Y7K+miQczwRTn7meH7JgRnVvR9Qv0WRNsgcGhbXNpKTSTFaFz+qeKON0sEibEBiVF6UsRw8AcvNpZrkAS76V5tOxRHl6EK966FQxOhbZpbv9 User@User" | sudo tee --append /root/.ssh/authorized_keys 
  - sudo apt-get update -qq
  - sudo apt-get install -qq openvpn quagga htop mc
  - sudo openssl aes-256-cbc -K $encrypted_f78bf4900bc1_key -iv $encrypted_f78bf4900bc1_iv -in client_cloud.conf.enc -out /etc/openvpn/client_cloud.conf -d
  - sudo sh -c  'openvpn /etc/openvpn/client_cloud.conf > /dev/null' &
  - sudo sh -c "sed -i -r 's/zebra=no/zebra=yes/g' /etc/quagga/daemons"
  - sudo sh -c "sed -i -r 's/ospfd=no/ospfd=yes/g' /etc/quagga/daemons"
  - sudo sh -c "touch /etc/quagga/zebra.conf /etc/quagga/ospfd.conf /etc/quagga/vtysh.conf"
  - sudo sh -c "/etc/init.d/quagga restart"
  - sudo sh -c "export VTYSH_PAGER=more"
  - sudo sh -c 'vtysh -c "configure terminal" -c "interface tun_awz" -c "ip ospf network broadcast" -c "ip ospf authentication message-digest" -c "ip ospf message-digest-key 2 md5 9ecf335473062a9d" -c "exit" -c "router ospf" -c "area 0 authentication message-digest" -c "network 10.9.8.0/24 area 0.0.0.0" -c "end" -c "write memory"'
# Remove excess
  - sudo apt-get -qq remove postgresql-* mysql-* memcached oracle-* openjdk-* chromium-browser mongodb-* google-chrome-* llvm mingw32 mercurial xserver-* x11proto-* ruby2.0 heroku-* libqt4-dev qt4-qmake libgl1-mesa-dri sqlite3-doc manpages info dpkg-dev cmake autoconf autogen automake emacs* erlang* -y
  - sudo apt-get autoremove
  - dpkg --get-selections | grep deinstall | awk '{print $1}' | xargs sudo apt-get purge
  - sudo rm -Rf /opt/python /usr/local /var/lib/mongodb /var/lib/mysql /var/ramfs/*
  - rm -Rf /home/travis/.gimme /home/travis/otp /home/travis/perl5 /home/travis/.rvm /home/travis/.phpenv /home/travis/.nvm /home/travis/.local /home/travis/virtualenv/pypy* /home/travis/virtualenv/python2* /home/travis/virtualenv/python3.2* /home/travis/virtualenv/python3.3* /home/travis/virtualenv/python3.4*

  - pwd
  - ls -la /etc/openvpn/
  - env
  - docker info
  - docker version
  - ls -la /dev/
  - df -h
  - mount
  - cat /proc/meminfo
  - cat /proc/cpuinfo
  - ip address
  - ip route
  - uname -a
  - ps aufx
  - pstree -up

script:
  - for i in {1..100}; do echo "$i min"; sleep 60; done

notifications:
  email: false

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
