---

sudo: required
language: python
python:
  - "3.5"

services:
  - docker
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq openvpn
  - sudo openssl aes-256-cbc -K $encrypted_f78bf4900bc1_key -iv $encrypted_f78bf4900bc1_iv -in client_cloud.conf.enc -out /etc/openvpn/client_cloud.conf -d
  - pwd
  - ls -la /etc/openvpn/
  - env
  - docker info
  - docker version
  - ls -la /dev/
  - df -h
  - mount
  - cat /proc/meminfo
  - cat /proc/cpuinfo
  - ip address
  - ip route
  - uname -a
  - ps aufx
  - pstree -up

script:
  - sleep 1


## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
