---

sudo: required
language: python
python:
  - "3.5"

before_install:
  - dpkg -l
  - sudo apt-get remove mysql postgres -y
  - env
  - df -h
  - mount
  - cat /proc/meminfo
  - cat /proc/cpuinfo
  - ip address
  - ip route
  - uname -a
  - ps aufx
  - pstree -up

script:
  - sleep 1


## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
